db:
  type_: postgresql
  connector: asyncpg
  host: localhost
  port: 5432
  login: login
  password: password
  database: name
  echo: false
api:
  host: localhost
  port: 8080
  debug: false
logging:
  level: DEBUG
  render_json_logs: false